### ISSUE TITLE
ParseInt error

### ISSUE THREAD

**Issue by millerlogic** [dnlo/coincapmon#1]
Hi, this is pretty cool.

I ended up getting many errors like the following,
```error converting string to int strconv.ParseInt: parsing "18651731995.1": invalid syntax```

though the program still works, the 24hr volume column is blank.

**Comment by dnlo** [comment]
Thanks, I've fixed the bug, you can download the new release [here](https://github.com/dnlo/coincapmon/releases/tag/v1.0.1)
